# Generated by Django 3.0 on 2022-05-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20220517_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
    ]
