# Generated by Django 3.0 on 2022-05-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20220519_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
